[tool.mypy]
python_version = "3.10"
packages = ["ignisc"]
exclude = ["venv"]
disable_error_code = [
    "no-redef",  # allow variable redefinition (needed for GObject.Property decorator)
    "method-assign",  # also needed for GObject.Property
    "import-not-found",
    "import-untyped"
]
mypy_path = ["stubs"]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["gi.repository.*"]
disable_error_code = ["assignment"]
